// ────────────────────────────────────────────────────────────
//  ip-devicer — shared types
// ────────────────────────────────────────────────────────────

export interface IpManagerOptions {
  /**
   * Polar license key that unlocks Pro or Enterprise tier features.
   *
   * | Tier         | Price    | Device limit | Servers   |
   * |--------------|---------|--------------|-----------|
   * | Free         | $0/mo    | 10,000       | —         |
   * | Pro          | $49/mo   | Unlimited    | 1 server  |
   * | Enterprise   | $299/mo  | Unlimited    | Unlimited |
   *
   * VPN/proxy detection and extended history require Pro or Enterprise.
   * Obtain a key at https://polar.sh and configure {@link POLAR_ORGANIZATION_ID}
   * and {@link POLAR_BENEFIT_IDS} in `src/libs/license.ts`.
   */
  licenseKey?: string;
  /** Path to GeoLite2-City.mmdb or GeoIP2-City.mmdb */
  maxmindPath?: string;
  /** Path to GeoLite2-ASN.mmdb or GeoIP2-ASN.mmdb */
  asnPath?: string;
  /** Enable reputation scoring (requires licenseKey for full signals) */
  enableReputation?: boolean;
  /** URL to fetch Tor exit node list from. Default: Tor Project bulk list */
  torExitListUrl?: string;
  /** Paths to plain-text CIDR files for VPN/proxy ranges (one CIDR per line) */
  proxyListPaths?: string[];
  /**
   * Enable RDAP lookups for ASN enrichment. Default: `true`.
   * Set to `false` to skip outbound RDAP network calls entirely.
   */
  enableRdap?: boolean;
  /** Max IP snapshots kept per deviceId in memory. Default: 50 (10 without key) */
  maxHistoryPerDevice?: number;
  /** Minimum km/h speed that triggers impossible-travel alert. Default: 900 */
  impossibleTravelThresholdKmh?: number;
  /**
   * Custom storage backend. Defaults to the built-in in-memory store.
   * Use `createSqliteIpStorage`, `createPostgresIpStorage`, or
   * `createRedisIpStorage` to supply a persistent backend.
   *
   * The `IpStorage` interface is synchronous (in-memory, SQLite).
   * For async backends (Postgres, Redis) initialise them separately and
   * wrap in an adapter that satisfies `IpStorage`, or use them standalone
   * via their own `AsyncIpStorage` interface.
   */
  storage?: import('./libs/adapters/inmemory.js').IpStorage | import('./libs/adapters/postgres.js').AsyncIpStorage;
}

// ── Geo / ASN ────────────────────────────────────────────────

export interface GeoData {
  country?: string;         // ISO 3166-1 alpha-2, e.g. "US"
  countryName?: string;     // English display name
  city?: string;
  subdivision?: string;     // First subdivision ISO code
  latitude?: number;
  longitude?: number;
  timezone?: string;
  asn?: number;
  asnOrg?: string;
}

// ── Enrichment result ────────────────────────────────────────

export interface IpEnrichment extends GeoData {
  isProxy: boolean;
  isVpn: boolean;
  isTor: boolean;
  isHosting: boolean;
	agentInfo?: {
		isAiAgent: boolean;
		aiAgentProvider?: string;
		aiAgentConfidence?: number; // 0–100
	}
	rdapInfo: { asn?: number; asnOrg?: string };
  riskScore: number;        // 0–100
  riskFactors: string[];
  consistencyScore: number; // 0–100 vs device history
  impossibleTravel: boolean;
}

// ── Storage ──────────────────────────────────────────────────

/** Stored IP enrichment snapshot associated with a resolved device ID. */
export interface IpSnapshot {
  /** Snapshot identifier generated by the storage backend. */
  id: string;
  /** Stable device identifier this snapshot belongs to. */
  deviceId: string;
  /** Capture timestamp for the snapshot. */
  timestamp: Date;
  /** IP address analyzed for this snapshot. */
  ip: string;
  /** Derived enrichment and risk signals for the IP address. */
  enrichment: IpEnrichment;
}

// ── Context passed alongside the FP payload ──────────────────

/** Per-request metadata passed from the host app into ip-devicer enrichment. */
export interface IpIdentifyContext {
  /** Explicit client IP override when middleware did not already resolve one. */
  ip?: string;
  /** Optional application-level user identifier associated with the device. */
  userId?: string;
  /** Raw request headers used for proxy-aware IP resolution. */
  headers?: Record<string, string | string[] | undefined>;
}

// ── Extended IdentifyResult ───────────────────────────────────

/** Baseline identify result shape expected from the upstream device manager. */
export interface IdentifyResult {
  /** Stable device identifier returned by fingerprint matching. */
  deviceId: string;
  /** Final confidence score after matching and enrichment. */
  confidence: number;
  /** Whether the incoming fingerprint was treated as a new device. */
  isNewDevice: boolean;
  /** Persisted mirror of `confidence` used for historical analysis. */
  matchConfidence: number;
  /** Linked application user ID when one was provided in context. */
  linkedUserId?: string;
  /** Cross-plugin enrichment metadata attached by post-processors. */
  enrichmentInfo: {
    plugins: string[];
    details: Record<string, Record<string, unknown>>;
    failures: Array<{ plugin: string; message: string }>;
  };
}

/** Identify result extended with IP-specific enrichment outputs. */
export interface EnrichedIdentifyResult extends IdentifyResult {
  /** Enriched geolocation, network-type, and risk metadata for the resolved IP. */
  ipEnrichment?: IpEnrichment;
  /** Signed delta between the current IP risk score and device history. */
  ipRiskDelta?: number;
}
